# Generated by Django 5.2.6 on 2025-09-17 11:50

import apps.prefeituras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da Prefeitura')),
                ('cidade', models.CharField(max_length=120, verbose_name='Cidade')),
                ('sigla_cidade', models.CharField(max_length=10, verbose_name='Sigla da cidade (ex.: MNC)')),
                ('codigo_ibge', models.CharField(max_length=10, verbose_name='Código IBGE')),
                ('dominio_email', models.CharField(blank=True, max_length=120, verbose_name='Domínio de e-mail institucional')),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to=apps.prefeituras.models.upload_logo_path, verbose_name='Logotipo')),
                ('secretario', models.CharField(blank=True, max_length=120, verbose_name='Secretário(a)')),
                ('diretor', models.CharField(blank=True, max_length=120, verbose_name='Diretor(a)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prefeitura',
                'verbose_name_plural': 'Prefeituras',
                'db_table': 'prefeituras_prefeitura',
                'ordering': ['cidade', 'nome'],
            },
        ),
    ]
