# Generated by Django 5.2.7 on 2025-10-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefeituras', '0002_prefeitura_lat_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefeitura',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ex.: -3.732700 (sul negativo). <a href="https://www.google.com/maps" target="_blank" rel="noopener">Abrir Google Maps</a>', max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='prefeitura',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ex.: -38.527000 (oeste negativo). <a href="https://www.google.com/maps" target="_blank" rel="noopener">Abrir Google Maps</a>', max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
