# Generated by Django 5.2.7 on 2025-11-10 17:37

import apps.processos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prefeituras', '0003_alter_prefeitura_latitude_alter_prefeitura_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(blank=True, default='ABERTO', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='prefeituras.prefeitura')),
            ],
            options={
                'db_table': 'proc_processo',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to=apps.processos.models.upload_foto_processo)),
                ('etapa_origem', models.CharField(choices=[('DEN', 'Denúncia'), ('NOT', 'Notificação'), ('AIF', 'Auto de Infração'), ('EMB', 'Embargo'), ('ITD', 'Interdição')], max_length=3)),
                ('origem_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(blank=True, null=True)),
                ('legenda', models.CharField(blank=True, max_length=140)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('largura_px', models.PositiveIntegerField(blank=True, null=True)),
                ('altura_px', models.PositiveIntegerField(blank=True, null=True)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('otimizada', models.BooleanField(default=False)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='processos.processo')),
            ],
            options={
                'db_table': 'proc_foto',
                'ordering': ['ordem', 'criada_em'],
            },
        ),
    ]
