# Generated by Django 5.2.7 on 2025-10-21 12:30

import apps.autoinfracao.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('denuncias', '0002_denunciaanexo_altura_px_denunciaanexo_hash_sha256_and_more'),
        ('notificacoes', '0004_alter_notificacao_protocolo'),
        ('prefeituras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoInfracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(editable=False, max_length=64, unique=True)),
                ('pessoa_tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=20)),
                ('nome_razao', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(default='CE', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Ex.: -3.876543', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Ex.: -38.654321', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('descricao', models.TextField(verbose_name='Descrição/Constatação')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20)),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('atualizada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aif_editados', to=settings.AUTH_USER_MODEL)),
                ('criada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aif_criados', to=settings.AUTH_USER_MODEL)),
                ('denuncia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='denuncias.denuncia')),
                ('fiscais', models.ManyToManyField(blank=True, related_name='autos_infracao', to=settings.AUTH_USER_MODEL)),
                ('notificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificacoes.notificacao')),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prefeituras.prefeitura')),
            ],
            options={
                'verbose_name': 'Auto de Infração',
                'verbose_name_plural': 'Autos de Infração',
                'db_table': 'aif_auto_infracao',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='AutoInfracaoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FOTO', 'Foto'), ('DOCUMENTO', 'Documento'), ('OUTRO', 'Outro')], default='FOTO', max_length=20)),
                ('arquivo', models.FileField(upload_to=apps.autoinfracao.models.upload_anexo_path_aif)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('largura_px', models.PositiveIntegerField(blank=True, null=True)),
                ('altura_px', models.PositiveIntegerField(blank=True, null=True)),
                ('hash_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('otimizada', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('auto_infracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='autoinfracao.autoinfracao')),
            ],
            options={
                'verbose_name': 'Anexo do AIF',
                'verbose_name_plural': 'Anexos do AIF',
                'db_table': 'aif_anexo',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='InfracaoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('nome', models.CharField(max_length=140)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prefeitura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prefeituras.prefeitura')),
            ],
            options={
                'verbose_name': 'Tipo de Infração',
                'verbose_name_plural': 'Tipos de Infração',
                'db_table': 'aif_infracao_tipo',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='tipos',
            field=models.ManyToManyField(blank=True, related_name='autos', to='autoinfracao.infracaotipo'),
        ),
    ]
