# Generated by Django 5.2.7 on 2025-10-21 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoinfracao', '0001_initial'),
        ('prefeituras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoinfracao',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área (m²)'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='area_mezanino_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área do mezanino (m²)'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='compartimentacao',
            field=models.BooleanField(default=False, verbose_name='Compartimentação (galpão)'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='divisorias',
            field=models.BooleanField(default=False, verbose_name='Divisórias (galpão)'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='duplex',
            field=models.BooleanField(default=False, verbose_name='Unidade duplex'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='mezanino',
            field=models.BooleanField(default=False, verbose_name='Possui mezanino'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='pe_direito_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pé-direito (m)'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='qtd_comodos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtd. de cômodos (casas)'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='testada_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Testada (m)'),
        ),
        migrations.CreateModel(
            name='Enquadramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('artigo', models.CharField(blank=True, max_length=60)),
                ('descricao', models.CharField(max_length=240)),
                ('valor_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prefeitura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prefeituras.prefeitura')),
            ],
            options={
                'verbose_name': 'Enquadramento Legal',
                'verbose_name_plural': 'Enquadramentos Legais',
                'db_table': 'aif_enquadramento',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='AutoInfracaoMultaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=240)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('auto_infracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='autoinfracao.autoinfracao')),
                ('enquadramento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autoinfracao.enquadramento')),
            ],
            options={
                'verbose_name': 'Item de Multa',
                'verbose_name_plural': 'Itens de Multa',
                'db_table': 'aif_multa_item',
                'ordering': ['-criada_em'],
            },
        ),
    ]
