# Generated by Django 5.2.7 on 2025-10-23 12:20

import apps.autoinfracao.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoinfracao', '0002_autoinfracao_area_m2_autoinfracao_area_mezanino_m2_and_more'),
        ('prefeituras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autoinfracao',
            name='prazo_regularizacao_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='valor_infracao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='valor_multa_homologado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='Embargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('VIGENTE', 'Vigente'), ('REGULARIZADO', 'Regularizado'), ('DESCUMPRIDO', 'Descumprido'), ('REVOGADO', 'Revogado'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=20)),
                ('licenca_tipo', models.CharField(blank=True, choices=[('REMEMBRAMENTO', 'Remembramento'), ('DESMEMBRAMENTO', 'Desmembramento'), ('CONSTRUCAO', 'Construção'), ('LOTEAMENTO', 'Loteamento'), ('DEMOLICAO', 'Demolição'), ('PUBLICIDADE', 'Publicidade'), ('LIC_INSTALACAO', 'Licença de Instalação'), ('CONSTR_RENOV', 'Construção/Renovação'), ('TERRAPLANAGEM', 'Terraplanagem'), ('DRENAGEM', 'Drenagem'), ('RELOTEAMENTO', 'Reloteamento'), ('INFRAESTRUTURA', 'Infraestrutura')], max_length=30, null=True)),
                ('exigencias_texto', models.TextField(blank=True)),
                ('prazo_regularizacao_data', models.DateField(blank=True, null=True)),
                ('afixado_no_local_em', models.DateTimeField(blank=True, null=True)),
                ('entregue_ao_responsavel_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('atualizada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embargos_editados', to=settings.AUTH_USER_MODEL)),
                ('auto_infracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embargos', to='autoinfracao.autoinfracao')),
                ('criada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embargos_criados', to=settings.AUTH_USER_MODEL)),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prefeituras.prefeitura')),
            ],
            options={
                'verbose_name': 'Embargo',
                'verbose_name_plural': 'Embargos',
                'db_table': 'aif_embargo',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='EmbargoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALVARA_CONSTRUCAO', 'Alvará de Construção / Regularização'), ('FOTO', 'Foto'), ('DOCUMENTO', 'Documento'), ('OUTRO', 'Outro')], default='DOCUMENTO', max_length=40)),
                ('arquivo', models.FileField(upload_to=apps.autoinfracao.models.upload_anexo_path_embargo)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('largura_px', models.PositiveIntegerField(blank=True, null=True)),
                ('altura_px', models.PositiveIntegerField(blank=True, null=True)),
                ('hash_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('otimizada', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('embargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='autoinfracao.embargo')),
            ],
            options={
                'verbose_name': 'Anexo do Embargo',
                'verbose_name_plural': 'Anexos do Embargo',
                'db_table': 'aif_embargo_anexo',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Interdicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('VIGENTE', 'Vigente'), ('REGULARIZADO', 'Regularizado'), ('DESCUMPRIDO', 'Descumprido'), ('REVOGADO', 'Revogado'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=20)),
                ('motivo_tipo', models.CharField(choices=[('PUBLICIDADE', 'Publicidade'), ('FUNCIONAMENTO', 'Funcionamento'), ('MP', 'Ministério Público (ofício)')], max_length=20)),
                ('condicoes_texto', models.TextField(blank=True)),
                ('prazo_regularizacao_data', models.DateField(blank=True, null=True)),
                ('afixado_no_local_em', models.DateTimeField(blank=True, null=True)),
                ('entregue_ao_responsavel_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('atualizada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interdicoes_editadas', to=settings.AUTH_USER_MODEL)),
                ('auto_infracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interdicoes', to='autoinfracao.autoinfracao')),
                ('criada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interdicoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prefeituras.prefeitura')),
            ],
            options={
                'verbose_name': 'Interdição',
                'verbose_name_plural': 'Interdições',
                'db_table': 'aif_interdicao',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='InterdicaoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALVARA_FUNCIONAMENTO', 'Alvará de Funcionamento'), ('FOTO', 'Foto'), ('DOCUMENTO', 'Documento'), ('OUTRO', 'Outro')], default='DOCUMENTO', max_length=40)),
                ('arquivo', models.FileField(upload_to=apps.autoinfracao.models.upload_anexo_path_interdicao)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('largura_px', models.PositiveIntegerField(blank=True, null=True)),
                ('altura_px', models.PositiveIntegerField(blank=True, null=True)),
                ('hash_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('otimizada', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('interdicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='autoinfracao.interdicao')),
            ],
            options={
                'verbose_name': 'Anexo da Interdição',
                'verbose_name_plural': 'Anexos da Interdição',
                'db_table': 'aif_interdicao_anexo',
                'ordering': ['-criada_em'],
            },
        ),
    ]
