# Generated by Django 5.2.7 on 2025-10-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoinfracao', '0010_rename_criada_por_to_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoinfracao',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('REGULARIZADO', 'Regularizado')], default='ABERTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='autoinfracaoanexo',
            name='tipo',
            field=models.CharField(choices=[('ALVARA_CONSTRUCAO', 'Alvará de Construção / Regularização'), ('ALVARA_FUNCIONAMENTO', 'Alvará de Funcionamento'), ('FOTO', 'Foto'), ('DOCUMENTO', 'Documento'), ('OUTRO', 'Outro')], default='FOTO', max_length=20),
        ),
    ]
