# Generated by Django 5.2.7 on 2025-11-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoinfracao', '0013_alter_autoinfracao_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoinfracao',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA', 'Transferência'), ('CARTAO', 'Cartão'), ('DINHEIRO', 'Dinheiro'), ('OUTRO', 'Outro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='guia_numero',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='observacao_pagamento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='pago_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
