# Generated by Django 5.2.7 on 2025-11-10 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoinfracao', '0014_autoinfracao_forma_pagamento_and_more'),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoinfracao',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autos', to='processos.processo'),
        ),
    ]
