# Generated by Django 5.2.6 on 2025-09-18 22:17

import apps.denuncias.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prefeituras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(blank=True, max_length=64, unique=True)),
                ('origem_denuncia', models.CharField(choices=[('CONTRIBUINTE', 'Contribuinte'), ('FISCAL', 'Fiscal')], default='CONTRIBUINTE', max_length=20)),
                ('denunciante_anonimo', models.BooleanField(default=False)),
                ('denunciante_nome', models.CharField(blank=True, max_length=120)),
                ('denunciante_email', models.EmailField(blank=True, max_length=254)),
                ('denunciante_telefone', models.CharField(blank=True, max_length=20)),
                ('denunciado_tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('denunciado_nome_razao', models.CharField(max_length=180)),
                ('denunciado_cpf_cnpj', models.CharField(blank=True, max_length=20)),
                ('denunciado_rg_ie', models.CharField(blank=True, max_length=20)),
                ('denunciado_email', models.EmailField(blank=True, max_length=254)),
                ('denunciado_telefone', models.CharField(blank=True, max_length=20)),
                ('denunciado_res_logradouro', models.CharField(blank=True, max_length=140)),
                ('denunciado_res_numero', models.CharField(blank=True, max_length=20)),
                ('denunciado_res_complemento', models.CharField(blank=True, max_length=60)),
                ('denunciado_res_bairro', models.CharField(blank=True, max_length=80)),
                ('denunciado_res_cidade', models.CharField(blank=True, max_length=80)),
                ('denunciado_res_uf', models.CharField(blank=True, max_length=2)),
                ('denunciado_res_cep', models.CharField(blank=True, max_length=9)),
                ('local_oco_logradouro', models.CharField(max_length=140)),
                ('local_oco_numero', models.CharField(blank=True, max_length=20)),
                ('local_oco_complemento', models.CharField(blank=True, max_length=60)),
                ('local_oco_bairro', models.CharField(max_length=80)),
                ('local_oco_cidade', models.CharField(max_length=80)),
                ('local_oco_uf', models.CharField(max_length=2)),
                ('local_oco_cep', models.CharField(blank=True, max_length=9)),
                ('local_oco_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('local_oco_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('descricao_oco', models.TextField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em análise'), ('ENCAMINHADA_NOTIFICACAO', 'Encaminhada para Notificação'), ('ARQUIVADA', 'Arquivada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=30)),
                ('procedencia', models.CharField(choices=[('INDETERMINADA', 'Indeterminada'), ('PROCEDE', 'Procede'), ('NAO_PROCEDE', 'Não procede')], default='INDETERMINADA', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('canal_registro', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo (tablet/portal)')], default='INTERNO', max_length=20)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_criadas', to=settings.AUTH_USER_MODEL)),
                ('denunciante_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_como_denunciante', to=settings.AUTH_USER_MODEL)),
                ('fiscais', models.ManyToManyField(blank=True, related_name='denuncias_atendidas', to=settings.AUTH_USER_MODEL)),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='prefeituras.prefeitura')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'db_table': 'denuncias_denuncia',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='DenunciaAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FOTO', 'Foto'), ('VIDEO', 'Vídeo'), ('DOCUMENTO', 'Documento')], default='DOCUMENTO', max_length=15)),
                ('arquivo', models.FileField(upload_to=apps.denuncias.models.upload_anexo_path)),
                ('observacao', models.CharField(blank=True, max_length=140)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='denuncias.denuncia')),
            ],
            options={
                'verbose_name': 'Anexo/Evidência',
                'verbose_name_plural': 'Anexos/Evidências',
                'db_table': 'denuncias_anexo',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='DenunciaDocumentoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MATRICULA', 'Matrícula do imóvel'), ('ESCRITURA', 'Escritura pública'), ('CONTRATO', 'Contrato de compra e venda'), ('IPTU', 'IPTU/Comprovantes'), ('OUTRO', 'Outro')], max_length=20)),
                ('arquivo', models.FileField(upload_to=apps.denuncias.models.upload_doc_imovel_path)),
                ('observacao', models.CharField(blank=True, max_length=140)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_imovel', to='denuncias.denuncia')),
            ],
            options={
                'verbose_name': 'Documento do imóvel',
                'verbose_name_plural': 'Documentos do imóvel',
                'db_table': 'denuncias_documento_imovel',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='DenunciaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('MUDANCA_STATUS', 'Mudança de status'), ('INCLUSAO_ANEXO', 'Inclusão de anexo'), ('INCLUSAO_DOC_IMOVEL', 'Inclusão de doc. do imóvel'), ('VINCULO_FISCAL', 'Vínculo de fiscal'), ('ALTERACAO_PROCEDENCIA', 'Alteração de procedência')], max_length=30)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('feito_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='denuncias.denuncia')),
                ('feito_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico da denúncia',
                'verbose_name_plural': 'Históricos da denúncia',
                'db_table': 'denuncias_historico',
                'ordering': ['-feito_em'],
            },
        ),
    ]
