# Generated by Django 5.2.6 on 2025-09-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denunciaanexo',
            name='altura_px',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denunciaanexo',
            name='hash_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='denunciaanexo',
            name='largura_px',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denunciaanexo',
            name='otimizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='denunciaanexo',
            name='tipo',
            field=models.CharField(choices=[('FOTO', 'Foto'), ('DOCUMENTO', 'Documento')], default='DOCUMENTO', max_length=15),
        ),
    ]
