# Generated by Django 5.2.7 on 2025-11-06 12:48

import apps.denuncias.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0010_alter_denuncia_local_oco_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DenunciaApontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=280)),
                ('atualizar_geo', models.BooleanField(default=False)),
                ('novo_lat', models.FloatField(blank=True, null=True)),
                ('novo_lng', models.FloatField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='denuncias.denuncia')),
            ],
            options={
                'db_table': 'denuncias_apontamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DenunciaApontamentoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.denuncias.models.upload_apontamento_path)),
                ('largura_px', models.IntegerField(blank=True, null=True)),
                ('altura_px', models.IntegerField(blank=True, null=True)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('otimizada', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('apontamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='denuncias.denunciaapontamento')),
            ],
            options={
                'db_table': 'denuncias_apontamento_anexo',
                'ordering': ['-criada_em'],
            },
        ),
    ]
