# Generated by Django 5.2.7 on 2025-10-16 16:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('denuncias', '0002_denunciaanexo_altura_px_denunciaanexo_hash_sha256_and_more'),
        ('prefeituras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(editable=False, max_length=30, unique=True)),
                ('pessoa_tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=20)),
                ('nome_razao', models.CharField(max_length=255, verbose_name='Nome / Razão Social')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(default='CE', max_length=2)),
                ('descricao', models.TextField(verbose_name='Descrição da irregularidade')),
                ('documento_tipo', models.CharField(blank=True, choices=[('RG', 'RG'), ('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('OUTRO', 'Outro')], max_length=30, null=True, verbose_name='Tipo de Documento')),
                ('prazo_regularizacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em Análise'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('atualizada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_editadas', to=settings.AUTH_USER_MODEL)),
                ('criada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('denuncia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='denuncias.denuncia')),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prefeituras.prefeitura')),
            ],
        ),
    ]
