# Generated by Django 5.2.7 on 2025-10-16 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ex.: -3.876543', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ex.: -38.654321', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude'),
        ),
    ]
