# Generated by Django 5.2.7 on 2025-10-16 18:27

import apps.notificacoes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_notificacao_latitude_notificacao_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FOTO', 'Foto'), ('DOCUMENTO', 'Documento'), ('OUTRO', 'Outro')], default='FOTO', max_length=20)),
                ('arquivo', models.FileField(upload_to=apps.notificacoes.models.upload_anexo_path_notificacao)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('largura_px', models.PositiveIntegerField(blank=True, null=True)),
                ('altura_px', models.PositiveIntegerField(blank=True, null=True)),
                ('hash_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('otimizada', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='notificacoes.notificacao')),
            ],
            options={
                'verbose_name': 'Anexo da Notificação',
                'verbose_name_plural': 'Anexos das Notificações',
                'db_table': 'notificacoes_anexo',
                'ordering': ['-criada_em'],
            },
        ),
    ]
