# Generated by Django 5.2.7 on 2025-10-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0003_notificacaoanexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='protocolo',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
