# Generated by Django 5.2.7 on 2025-10-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0004_alter_notificacao_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área (m²)'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='area_mezanino_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área do mezanino (m²)'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='compartimentacao',
            field=models.BooleanField(default=False, verbose_name='Compartimentação (galpão)'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='divisorias',
            field=models.BooleanField(default=False, verbose_name='Divisórias (galpão)'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='duplex',
            field=models.BooleanField(default=False, verbose_name='Unidade duplex'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='mezanino',
            field=models.BooleanField(default=False, verbose_name='Possui mezanino'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='pe_direito_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pé-direito (m)'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='qtd_comodos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtd. de cômodos (casas)'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='testada_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Testada (m)'),
        ),
    ]
