# Generated by Django 5.2.7 on 2025-10-30 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0008_notificacao_vinculos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Ex.: -3.876543', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Ex.: -38.654321', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude'),
        ),
    ]
