# Generated by Django 5.2.7 on 2025-11-10 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0009_alter_notificacao_latitude_and_more'),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='processos.processo'),
        ),
    ]
