# Generated by Django on 2025-11-11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0010_notificacao_processo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='fiscais',
            field=models.ManyToManyField(blank=True, related_name='notificacoes_atendidas', to=settings.AUTH_USER_MODEL),
        ),
    ]

