# Generated by Django 5.2.7 on 2025-11-13 18:30

import apps.notificacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0012_notificacao_ocorrido_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='conclusao_documento',
            field=models.FileField(blank=True, null=True, upload_to=apps.notificacoes.models.Notificacao.upload_conclusao_path),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='conclusao_motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
