# Generated by Django 5.2.7 on 2025-10-31 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefeituras', '0003_alter_prefeitura_latitude_alter_prefeitura_longitude'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('prefeitura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logins_usuario', to='prefeituras.prefeitura')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login de Usuário (auditoria)',
                'verbose_name_plural': 'Logins de Usuários (auditoria)',
                'db_table': 'usuarios_login_log',
                'ordering': ['-criado_em'],
            },
        ),
    ]
