# Generated by Django 5.2.7 on 2025-11-03 13:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefeituras', '0003_alter_prefeitura_latitude_alter_prefeitura_longitude'),
        ('usuarios', '0003_loginlog_rename_and_logout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariologinlog',
            options={'ordering': ['-logado_em'], 'verbose_name': 'Login de Usuário (auditoria)', 'verbose_name_plural': 'Logins de Usuários (auditoria)'},
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('VIEW', 'Visualizou'), ('CREATE', 'Criou'), ('UPDATE', 'Editou'), ('DELETE', 'Excluiu'), ('PRINT', 'Imprimiu'), ('LINK', 'Vinculou'), ('UNLINK', 'Desvinculou'), ('OTHER', 'Outra Ação')], default='VIEW', max_length=12)),
                ('recurso', models.CharField(blank=True, max_length=60)),
                ('app_label', models.CharField(blank=True, max_length=60)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=60)),
                ('url', models.CharField(max_length=300)),
                ('metodo', models.CharField(max_length=8)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('prefeitura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='prefeituras.prefeitura')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios_audit_log',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['prefeitura', 'usuario', 'acao', 'criado_em'], name='usuarios_au_prefeit_64d246_idx')],
            },
        ),
    ]
