# Generated by Django 5.2.7 on 2025-10-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='imovel',
            new_name='cad_imovel_prefeit_4fc6bf_idx',
            old_name='cad_imove_prefeitu_eab0d7_idx',
        ),
        migrations.RenameIndex(
            model_name='imovel',
            new_name='cad_imovel_prefeit_306592_idx',
            old_name='cad_imove_prefeitu_75f0f4_idx',
        ),
        migrations.RenameIndex(
            model_name='imovelvinculo',
            new_name='cad_imovel__imovel__7cf358_idx',
            old_name='cad_imove_imovel_i_d5f8f8_idx',
        ),
        migrations.RenameIndex(
            model_name='pessoa',
            new_name='cad_pessoa_prefeit_426ef1_idx',
            old_name='cad_pesso_prefeitu_2d49a1_idx',
        ),
        migrations.RenameIndex(
            model_name='pessoa',
            new_name='cad_pessoa_prefeit_cd0045_idx',
            old_name='cad_pesso_prefeitu_3d2e5a_idx',
        ),
    ]
